site_name: LINDA+

nav:
    - Home: index.md
    - Documentation: documentation.md
    - Tutorials: tutorial.md
    - Downloads: download.md
    - About: about.md
theme: readthedocs

docs_dir: docs
site_dir: '_site_mkdocs/'
repo_url: 'https://github.com/enio23/lindaplus-docs'
site_url: 'https://github.com/enio23/lindaplus-docs'
use_directory_urls: false
repo_name: 'GitHub'
prev_next_buttons_location: 'both'
copyright: 'Enio Oleg Gjerga'
