site_name: 'LINDA+'
site_description: 'Documentation page of the LINDA+ software.'
repo_url: 'https://github.com/dieterich-lab/LINDAPlus'
repo_name: 'GitHub'
docs_dir: 'docs/'
site_dir: '_site_mkdocs/'
theme: 'readthedocs'
prev_next_buttons_location: 'both'
copyright: 'Enio Oleg Gjerga'
